ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "modelUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "modelPosterUrl" TEXT;
ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "modelUrl" TEXT;
