import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Boxes, CheckCircle2, Clock3, MapPin, PackageCheck, ShieldCheck, XCircle } from "lucide-react";
import { DynamicMedia } from "@/components/storefront/dynamic-media";
import { ServiceBookingForm } from "@/components/storefront/service-booking-form";
import { getPublishedService, packageAvailableStock } from "@/lib/platform-content";
import { money } from "@/lib/utils";

type Props = { params: Promise<{ slug: string }>; searchParams: Promise<{ package?: string }> };
export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const service = await getPublishedService(slug); return service ? { title: service.seoTitle || `${service.name} | HTC Services`, description: service.seoDescription || service.shortDescription } : { title: "Service not found" }; }

export default async function ServiceDetailPage({ params, searchParams }: Props) {
  const { slug } = await params;
  const selectedPackageId = (await searchParams).package || "";
  const service = await getPublishedService(slug);
  if (!service) notFound();
  const gallery = Array.isArray(service.gallery) ? service.gallery.map(String) : [];
  return <main className="pb-16 pt-24"><section className="mx-auto grid max-w-[90rem] gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[minmax(0,1.1fr)_minmax(360px,.9fr)] lg:px-10"><div><div className="relative aspect-[16/10] overflow-hidden rounded-lg bg-slate-100"><DynamicMedia src={service.coverImage} alt={service.imageAlt || service.name} priority/></div>{gallery.length ? <div className="mt-3 grid grid-cols-3 gap-3">{gallery.slice(0, 6).map((image, index) => <div key={`${image}-${index}`} className="relative aspect-[4/3] overflow-hidden rounded-md bg-slate-100"><DynamicMedia src={image} alt={`${service.name} gallery ${index + 1}`}/></div>)}</div> : null}</div><aside className="h-fit lg:sticky lg:top-24"><p className="showroom-eyebrow text-red-700">{service.category?.name || "HTC Room Services"} · {service.serviceMode.replaceAll("_", " ")}</p><h1 className="mt-3 font-display text-6xl font-black uppercase leading-[.85]">{service.name}</h1><p className="mt-5 text-base leading-7 text-slate-600">{service.description}</p>{service.laborPricingNote ? <p className="mt-4 border-l-2 border-red-700 pl-4 text-sm font-semibold leading-6 text-slate-700">{service.laborPricingNote}</p> : null}<div className="mt-6 grid gap-2 sm:grid-cols-2"><p className="flex items-center gap-2 rounded-lg bg-slate-100 p-3 text-sm font-bold"><Clock3 size={17} className="text-red-700"/>{service.estimatedCompletionTime || "Schedule confirmed after review"}</p><p className="flex items-center gap-2 rounded-lg bg-slate-100 p-3 text-sm font-bold"><MapPin size={17} className="text-red-700"/>{service.cities.length ? service.cities.join(", ") : "Service areas confirmed on request"}</p><p className="flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-bold text-emerald-800"><ShieldCheck size={17}/>{service.warrantyInformation || "Professional installation support"}</p><p className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm font-bold text-red-800">{service.fixedPrice ? money(Number(service.fixedPrice)) : service.startingPrice ? `From ${money(Number(service.startingPrice))}` : "Quotation after review"}</p></div>{service.siteVisitRequired ? <p className="mt-3 text-xs font-bold text-slate-500">Site visit required{Number(service.siteVisitFee) > 0 ? ` · ${money(Number(service.siteVisitFee))} visit fee` : " · fee confirmed by HTC"}</p> : null}</aside></section>
    <section className="mx-auto grid max-w-[90rem] gap-6 px-4 py-8 sm:px-6 lg:grid-cols-2 lg:px-10"><WorkList title="Included work" items={service.includedWork} icon="check"/><WorkList title="Not included" items={service.excludedWork} icon="x"/></section>
    {service.packages.length ? <section className="mx-auto max-w-[90rem] px-4 py-8 sm:px-6 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="showroom-eyebrow text-red-700">Material starting scopes</p><h2 className="mt-2 font-display text-4xl font-black uppercase">Room bundles linked to this service</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">These are supply-only product bundles. Select one as the material scope for this installation request; HTC confirms measurements, labour and the final installed quotation.</p></div><Boxes className="text-red-700" size={28}/></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{service.packages.map((bundle) => { const stock = packageAvailableStock(bundle.items); return <article key={bundle.id} className="premium-card overflow-hidden p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-black uppercase text-red-700">{bundle.sku} · {bundle.roomType}</p><h3 className="mt-2 font-display text-3xl font-black uppercase leading-none">{bundle.name}</h3></div>{bundle.badge ? <span className="rounded-md bg-red-50 px-2 py-1 text-[10px] font-black uppercase text-red-700">{bundle.badge}</span> : null}</div><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600">{bundle.shortDescription || bundle.description}</p><div className="mt-4 grid gap-2 border-y border-slate-100 py-4 text-xs font-bold"><span className="flex items-center justify-between"><span>{bundle.items.length} material lines</span><strong>{money(Number(bundle.finalPrice))}</strong></span><span className={`flex items-center justify-between ${stock > 0 ? "text-emerald-700" : "text-red-700"}`}><span>Live bundle stock</span><strong>{stock}</strong></span></div><div className="mt-4 flex gap-2"><Link href={`/services/${service.slug}?package=${bundle.id}#book`} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-md bg-red-700 px-4 text-sm font-black text-white transition hover:bg-red-600"><PackageCheck size={17}/> Use in service request</Link><Link href={`/packages/${bundle.slug}`} className="grid size-11 place-items-center rounded-md border border-slate-200 transition hover:border-red-300 hover:text-red-700" aria-label={`View ${bundle.name}`}><ArrowRight size={17}/></Link></div></article>; })}</div></section> : null}
    {service.bookingEnabled ? <section id="book" className="mx-auto scroll-mt-28 max-w-[90rem] px-4 py-8 sm:px-6 lg:px-10"><div className="showroom-panel p-5 sm:p-8"><p className="showroom-eyebrow text-red-700">Private request</p><h2 className="mt-2 font-display text-4xl font-black uppercase">Book {service.name}</h2><p className="mt-2 text-sm text-slate-500">Submit site details. Selected package products are saved with the request and the admin confirms the final quotation.</p><div className="mt-6"><ServiceBookingForm serviceId={service.id} serviceName={service.name} availableTimeSlots={service.availableTimeSlots} initialPackageId={selectedPackageId} packages={service.packages.map((bundle) => ({ id: bundle.id, name: bundle.name, sku: bundle.sku, finalPrice: Number(bundle.finalPrice), itemCount: bundle.items.length }))}/></div></div></section> : null}
    {service.products.length ? <section className="mx-auto max-w-[90rem] px-4 py-8 sm:px-6 lg:px-10"><h2 className="font-display text-4xl font-black uppercase">Related hardware</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{service.products.map(({ product }) => <Link key={product.id} href={`/products/${product.slug}`} className="premium-card flex items-center gap-4 p-3"><div className="relative size-20 shrink-0 overflow-hidden rounded-md bg-slate-100"><DynamicMedia src={product.images[0]?.url} alt={product.name}/></div><div><strong>{product.name}</strong><p className="mt-1 text-sm text-slate-500">{product.sku}</p><p className="mt-1 font-black text-red-700">{money(Number(product.price))}</p></div></Link>)}</div></section> : null}
  </main>;
}

function WorkList({ title, items, icon }: { title: string; items: string[]; icon: "check" | "x" }) { const Icon = icon === "check" ? CheckCircle2 : XCircle; return <div className="showroom-panel p-5"><h2 className="font-display text-3xl font-black uppercase">{title}</h2><div className="mt-4 grid gap-2">{items.length ? items.map((item) => <p key={item} className="flex items-start gap-2 rounded-lg bg-slate-50 p-3 text-sm"><Icon size={17} className={icon === "check" ? "mt-0.5 text-emerald-600" : "mt-0.5 text-slate-400"}/>{item}</p>) : <p className="text-sm text-slate-500">Details are confirmed with your quotation.</p>}</div></div>; }
